CREATE TABLE `matches` (
	`id` text PRIMARY KEY NOT NULL,
	`updated_at` integer,
	`created_at` integer NOT NULL,
	`deleted_at` integer,
	`user1` text NOT NULL,
	`user2` text NOT NULL,
	`track` text NOT NULL,
	`session` text,
	`winner` text,
	`duration_ms` integer,
	`stage` text,
	`comment` text,
	`status` text NOT NULL,
	FOREIGN KEY (`user1`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`user2`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`track`) REFERENCES `tracks`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`session`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`winner`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
