name: SonarQube

on:
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'common/**'
      - 'drizzle/**'
      - 'drizzle.config.ts'
      - 'vite.config.ts'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - '.github/workflows/sonarqube.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run SonarQube checks
    runs-on: ubuntu-latest
    env:
      SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
